// <auto-generated />
using System;
using Entities.Entities;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Entities.Migrations
{
    [DbContext(typeof(TiendaGeekContext))]
    partial class TiendaGeekContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Entities.Entities.Carrito", b =>
                {
                    b.Property<int>("CodigoCarrito")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoCarrito"));

                    b.Property<int?>("CodigoProducto")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuario")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalCompra")
                        .HasColumnType("decimal(10, 2)");

                    b.HasKey("CodigoCarrito")
                        .HasName("PK__Carrito__20E75EFA8E9F4FB3");

                    b.HasIndex("CodigoProducto");

                    b.HasIndex("CodigoUsuario");

                    b.ToTable("Carrito", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Categorium", b =>
                {
                    b.Property<int>("CodigoCategoria")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoCategoria"));

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CodigoCategoria")
                        .HasName("PK__Categori__3CEE2F4C97C23F2E");

                    b.ToTable("Categoria");
                });

            modelBuilder.Entity("Entities.Entities.ImagenProducto", b =>
                {
                    b.Property<int>("CodigoImagen")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoImagen"));

                    b.Property<int?>("CodigoProducto")
                        .HasColumnType("int");

                    b.Property<string>("RutaImagen")
                        .HasMaxLength(255)
                        .IsUnicode(false)
                        .HasColumnType("varchar(255)");

                    b.HasKey("CodigoImagen")
                        .HasName("PK__ImagenPr__B3306E29F2199085");

                    b.HasIndex("CodigoProducto");

                    b.ToTable("ImagenProducto", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Orden", b =>
                {
                    b.Property<int>("CodigoOrden")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoOrden"));

                    b.Property<int?>("CodigoCarrito")
                        .HasColumnType("int");

                    b.Property<int?>("CodigoUsuario")
                        .HasColumnType("int");

                    b.Property<DateOnly?>("FechaOrden")
                        .HasColumnType("date");

                    b.HasKey("CodigoOrden")
                        .HasName("PK__Orden__1B9107A53D769B3D");

                    b.HasIndex("CodigoCarrito");

                    b.HasIndex("CodigoUsuario");

                    b.ToTable("Orden", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Producto", b =>
                {
                    b.Property<int>("CodigoProducto")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoProducto"));

                    b.Property<int?>("CodigoCategoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<decimal?>("Precio")
                        .HasColumnType("decimal(10, 2)");

                    b.Property<int?>("Unidades")
                        .HasColumnType("int");

                    b.HasKey("CodigoProducto")
                        .HasName("PK__Producto__785B009E79A2EC7E");

                    b.HasIndex("CodigoCategoria");

                    b.ToTable("Producto", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Usuario", b =>
                {
                    b.Property<int>("CodigoUsuario")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CodigoUsuario"));

                    b.Property<string>("Contrasena")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<bool?>("Estado")
                        .HasColumnType("bit");

                    b.Property<string>("Nombre")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("PrimerApellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.Property<string>("Rol")
                        .HasMaxLength(50)
                        .IsUnicode(false)
                        .HasColumnType("varchar(50)");

                    b.Property<string>("SegundoApellido")
                        .HasMaxLength(100)
                        .IsUnicode(false)
                        .HasColumnType("varchar(100)");

                    b.HasKey("CodigoUsuario")
                        .HasName("PK__Usuario__F0C18F58F2C219AA");

                    b.ToTable("Usuario", (string)null);
                });

            modelBuilder.Entity("Entities.Entities.Carrito", b =>
                {
                    b.HasOne("Entities.Entities.Producto", "CodigoProductoNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("CodigoProducto")
                        .HasConstraintName("FK__Carrito__CodigoP__5441852A");

                    b.HasOne("Entities.Entities.Usuario", "CodigoUsuarioNavigation")
                        .WithMany("Carritos")
                        .HasForeignKey("CodigoUsuario")
                        .HasConstraintName("FK__Carrito__CodigoU__534D60F1");

                    b.Navigation("CodigoProductoNavigation");

                    b.Navigation("CodigoUsuarioNavigation");
                });

            modelBuilder.Entity("Entities.Entities.ImagenProducto", b =>
                {
                    b.HasOne("Entities.Entities.Producto", "CodigoProductoNavigation")
                        .WithMany("ImagenProductos")
                        .HasForeignKey("CodigoProducto")
                        .HasConstraintName("FK__ImagenPro__Codig__5070F446");

                    b.Navigation("CodigoProductoNavigation");
                });

            modelBuilder.Entity("Entities.Entities.Orden", b =>
                {
                    b.HasOne("Entities.Entities.Carrito", "CodigoCarritoNavigation")
                        .WithMany("Ordens")
                        .HasForeignKey("CodigoCarrito")
                        .HasConstraintName("FK__Orden__CodigoCar__5812160E");

                    b.HasOne("Entities.Entities.Usuario", "CodigoUsuarioNavigation")
                        .WithMany("Ordens")
                        .HasForeignKey("CodigoUsuario")
                        .HasConstraintName("FK__Orden__CodigoUsu__571DF1D5");

                    b.Navigation("CodigoCarritoNavigation");

                    b.Navigation("CodigoUsuarioNavigation");
                });

            modelBuilder.Entity("Entities.Entities.Producto", b =>
                {
                    b.HasOne("Entities.Entities.Categorium", "CodigoCategoriaNavigation")
                        .WithMany("Productos")
                        .HasForeignKey("CodigoCategoria")
                        .HasConstraintName("FK__Producto__Codigo__4D94879B");

                    b.Navigation("CodigoCategoriaNavigation");
                });

            modelBuilder.Entity("Entities.Entities.Carrito", b =>
                {
                    b.Navigation("Ordens");
                });

            modelBuilder.Entity("Entities.Entities.Categorium", b =>
                {
                    b.Navigation("Productos");
                });

            modelBuilder.Entity("Entities.Entities.Producto", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("ImagenProductos");
                });

            modelBuilder.Entity("Entities.Entities.Usuario", b =>
                {
                    b.Navigation("Carritos");

                    b.Navigation("Ordens");
                });
#pragma warning restore 612, 618
        }
    }
}
